---
- name: create tomcat group
  group:
      name: tomcat
      state: present 

- name: create tomcate user
  user:
    name: tomcat
    shell: /bin/false
    group: tomcat
    home: /opt/tomcat
    state: present 